### ISSUE TITLE
For Reindex

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/amihaiemil.github.io#14]
Issue for reindexing the website

**Comment by amihaiemil** [comment]
@charlesmike delete

**Comment by charlesmike** [comment]
> @charlesmike delete

@amihaiemil the repository's name in a delete command has to be between single back apostrophes.
and it has to match the actual reponame exactly (case sensitive) 

A valid delete command here is ``@charlesmike delete `amihaiemil.github.io` index``.

**Comment by amihaiemil** [comment]
@charlesmike delete `amihaiemil.github.io` index

**Comment by charlesmike** [comment]
> @charlesmike delete `amihaiemil.github.io` index

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See [logs](http://charles.amihaiemil.com/logs.html?log=/cd700497-e7bc-4b78-a907-faafccfa9919.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/ebfef020-3bab-4c46-a628-790bd3e1b0c8.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/ebfef020-3bab-4c46-a628-790bd3e1b0c8.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/141ef9b0-f0cf-4e0d-8d1e-05fff39320af.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/141ef9b0-f0cf-4e0d-8d1e-05fff39320af.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/bc037f6d-f09d-4a54-8de1-a1a0f2510508.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/1f94b9e2-0f41-4051-9ce1-3ae39024625d.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/1f94b9e2-0f41-4051-9ce1-3ae39024625d.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/213696e5-5aaf-4be2-8abe-4f947e1f5544.log).

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/213696e5-5aaf-4be2-8abe-4f947e1f5544.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2017/02/13/github-automatically-deploy-files-from-one-repo-to-another.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/02/13/github-automatically-deploy-files-from-one-repo-to-another.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/a2076666-22eb-4096-bceb-130b679d02fc.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/02/13/github-automatically-deploy-files-from-one-repo-to-another.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/a2076666-22eb-4096-bceb-130b679d02fc.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2017/04/05/the-remote-dream.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/04/05/the-remote-dream.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/ec6d7223-dd40-4a79-8a20-e4627bbfe55b.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/04/05/the-remote-dream.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/ec6d7223-dd40-4a79-8a20-e4627bbfe55b.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2017/03/22/puzzles-and-open-source.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/03/22/puzzles-and-open-source.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/d8d41ca0-88bd-46fd-b847-efbfe80d3bf5.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/03/22/puzzles-and-open-source.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/d8d41ca0-88bd-46fd-b847-efbfe80d3bf5.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2017/03/13/cms-for-clientside.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/03/13/cms-for-clientside.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/563d168b-8e31-40fb-a01d-da782ae8d62d.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/03/13/cms-for-clientside.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/563d168b-8e31-40fb-a01d-da782ae8d62d.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2017/02/24/each-system-property-a-class.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/02/24/each-system-property-a-class.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/12cdc6da-8e9a-4c4a-86f8-4bbfaa1bd712.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/02/24/each-system-property-a-class.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/12cdc6da-8e9a-4c4a-86f8-4bbfaa1bd712.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2017/02/18/decorators-with-tunnels.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/02/18/decorators-with-tunnels.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/83cbd854-fc3c-4632-868f-381426d7e436.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/02/18/decorators-with-tunnels.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/83cbd854-fc3c-4632-868f-381426d7e436.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2017/01/24/selenium-and-junit-the-right-way.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/01/24/selenium-and-junit-the-right-way.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/7ae3a484-f2bc-4866-9f8e-1c47ac57049a.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/01/24/selenium-and-junit-the-right-way.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/7ae3a484-f2bc-4866-9f8e-1c47ac57049a.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2016/12/30/becoming-a-contributor.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/12/30/becoming-a-contributor.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/537d583e-f44a-44ae-8824-23b7188ac297.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/12/30/becoming-a-contributor.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/537d583e-f44a-44ae-8824-23b7188ac297.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2016/12/22/contributors-wanted.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/12/22/contributors-wanted.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/fd4da311-b507-4332-bd7e-4a7bd2f0435a.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/12/22/contributors-wanted.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/fd4da311-b507-4332-bd7e-4a7bd2f0435a.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2016/12/05/project-charles.html page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/12/05/project-charles.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/68f58b07-c1f0-40cd-a967-9e739738c638.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/12/05/project-charles.html) page

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/68f58b07-c1f0-40cd-a967-9e739738c638.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2016/12/05/project-charles.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/12/05/project-charles.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/d0eb6091-3a55-4cdc-9de6-cdd5c45d2f68.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/12/05/project-charles.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/d0eb6091-3a55-4cdc-9de6-cdd5c45d2f68.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2016/06/03/using-google-recaptha-with-jax-rs.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/06/03/using-google-recaptha-with-jax-rs.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/a73e9047-cb38-410b-8c30-41ccc78ce315.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/06/03/using-google-recaptha-with-jax-rs.html) page

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/a73e9047-cb38-410b-8c30-41ccc78ce315.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2016/06/03/using-google-recaptha-with-jax-rs.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/06/03/using-google-recaptha-with-jax-rs.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/c266775e-fc48-4e7a-9ade-c6c63b3ff31d.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/06/03/using-google-recaptha-with-jax-rs.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/c266775e-fc48-4e7a-9ade-c6c63b3ff31d.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2016/05/24/calculate-time-with-javascript.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/05/24/calculate-time-with-javascript.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/31e7f5d9-989b-45bc-97bf-de47c321a8dc.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/05/24/calculate-time-with-javascript.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/31e7f5d9-989b-45bc-97bf-de47c321a8dc.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2016/05/07/what-is-hateoas.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/05/07/what-is-hateoas.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/9cd450f2-1210-4452-837e-3155d8d9c434.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/05/07/what-is-hateoas.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/9cd450f2-1210-4452-837e-3155d8d9c434.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2016/04/20/project-eva.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/04/20/project-eva.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/0afc33e5-e11b-4266-9f3b-ef0b8dfc8066.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/04/20/project-eva.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/0afc33e5-e11b-4266-9f3b-ef0b8dfc8066.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2016/04/09/hello-world.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/04/09/hello-world.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/fe36c71d-c5db-4aca-bdbf-9dc308aaba19.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2016/04/09/hello-world.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/fe36c71d-c5db-4aca-bdbf-9dc308aaba19.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)
