### ISSUE TITLE
Meet Charles Michael

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/amihaiemil.github.io#20]
For indexing

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/2017/05/23/meet-charles-michael.html) page, it describes how everything works

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/05/23/meet-charles-michael.html) page, it describes how everything works

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/3d04fbe3-41f9-4582-96fb-f58a9782cbfe.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/2017/05/23/meet-charles-michael.html) page, it describes how everything works

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/3d04fbe3-41f9-4582-96fb-f58a9782cbfe.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike try to index [this](http://amihaiemil.github.io/sitemap.xml) sitemap pls

**Comment by amihaiemil** [comment]
@charlesmike try to index [this](http://amihaiemil.github.io/sitemap.xml) sitemap pls

**Comment by charlesmike** [comment]
> @charlesmike try to index [this](http://amihaiemil.github.io/sitemap.xml) sitemap pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/202de27f-8ec1-4301-a577-575df9bafdf9.log).

**Comment by charlesmike** [comment]
> @charlesmike try to index [this](http://amihaiemil.github.io/sitemap.xml) sitemap pls

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/202de27f-8ec1-4301-a577-575df9bafdf9.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike pls index [this](http://amihaiemil.github.io/2017/06/14/non-flushable-jsonobjectbuilder.html) page

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://amihaiemil.github.io/2017/06/14/non-flushable-jsonobjectbuilder.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/0b9a5d9b-f874-47ce-ac3e-b01fdb12002f.log).

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://amihaiemil.github.io/2017/06/14/non-flushable-jsonobjectbuilder.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/0b9a5d9b-f874-47ce-ac3e-b01fdb12002f.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike please indes [this](http://amihaiemil.github.io/2017/07/04/yasson-yet-another-POJO-parser.html) new article

**Comment by charlesmike** [comment]
> @charlesmike please index [this](http://amihaiemil.github.io/2017/07/04/yasson-yet-another-POJO-parser.html) new article

@amihaiemil sorry I do not understand you. See [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post for more details.

**Comment by amihaiemil** [comment]
@charlesmike please index [this](http://amihaiemil.github.io/2017/07/04/yasson-yet-another-POJO-parser.html) new page

**Comment by charlesmike** [comment]
> @charlesmike please index [this](http://amihaiemil.github.io/2017/07/04/yasson-yet-another-POJO-parser.html) new page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/61522e88-74a2-4a59-954f-a2ecc448a274.log).

**Comment by charlesmike** [comment]
> @charlesmike please index [this](http://amihaiemil.github.io/2017/07/04/yasson-yet-another-POJO-parser.html) new page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/61522e88-74a2-4a59-954f-a2ecc448a274.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike pls index [this](http://amihaiemil.github.io/2017/07/14/selenium-headless-chrome-travis.html) new page

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://amihaiemil.github.io/2017/07/14/selenium-headless-chrome-travis.html) new page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/066ec4a8-0ea5-43d2-93b8-2ab843f8b86b.log).

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://amihaiemil.github.io/2017/07/14/selenium-headless-chrome-travis.html) new page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/066ec4a8-0ea5-43d2-93b8-2ab843f8b86b.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike pls index [this](http://amihaiemil.github.io/2017/08/12/how-interfaces-are-refactoring-our-code.html) new page

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://amihaiemil.github.io/2017/08/12/how-interfaces-are-refactoring-our-code.html) new page 

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/0298e214-f32c-4b7d-a896-34c368e704b0.log).

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://amihaiemil.github.io/2017/08/12/how-interfaces-are-refactoring-our-code.html) new page 

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/0298e214-f32c-4b7d-a896-34c368e704b0.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike hello, are you there?

**Comment by charlesmike** [comment]
> @charlesmike hello, are you there?

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).
Also, [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post might be useful.

**Comment by amihaiemil** [comment]
@charlesmike hello there! Is the webhook working?

**Comment by charlesmike** [comment]
> @charlesmike hello there! Is the webhook working?

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).
Also, [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post might be useful.

**Comment by amihaiemil** [comment]
@charlesmike pls index [this](http://amihaiemil.github.io/2017/09/01/data-should-be-animated-not-represented.html) new page

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://amihaiemil.github.io/2017/09/01/data-should-be-animated-not-represented.html) new page 

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/7d48a25c-95bb-4c41-aabb-85295a9ef202.log).

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://amihaiemil.github.io/2017/09/01/data-should-be-animated-not-represented.html) new page 

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/7d48a25c-95bb-4c41-aabb-85295a9ef202.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike delete the index of `amihaiemil.github.io` pls

**Comment by charlesmike** [comment]
> @charlesmike delete the index of `amihaiemil.github.io` pls

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See [logs](http://charles.amihaiemil.com/logs.html?log=/dfb05a56-bd04-451a-b4be-8eed2f29aacb.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike pls index [this](http://www.amihaiemil.com/sitemap.xml) sitemap

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://www.amihaiemil.com/sitemap.xml) sitemap

@amihaiemil the given page or sitemap does not seem to belong to the website hosted in this repo!

Make sure that the link starts with ``http://`` or ``https://`` followed by``yourusername.github.io/...``. Do not use the CNAME or any other domain, even if it redirects toa page from this repo. Also, make sure that the link is specified in Markdown format. 

 If this condition is met and it still doesn't work please open an issue [here](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike pls index [this](http://amihaiemil.github.io/sitemap.xml) sitemap

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://amihaiemil.github.io/sitemap.xml) sitemap

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/a59c9e08-70f0-4a91-91ee-ae55d238ba0d.log).

**Comment by amihaiemil** [comment]
@charlesmike pls index [this](http://amihaiemil.github.io/2017/10/03/letsencrypt-glassfish-ec2.html) new page

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://amihaiemil.github.io/2017/10/03/letsencrypt-glassfish-ec2.html) new page 

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/55c9612f-648e-4923-94cd-f4881a73b582.log).

**Comment by charlesmike** [comment]
> @charlesmike pls index [this](http://amihaiemil.github.io/2017/10/03/letsencrypt-glassfish-ec2.html) new page 

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/55c9612f-648e-4923-94cd-f4881a73b582.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@comdor hello there

**Comment by comdor** [comment]
@amihaiemil Hi there! I'm only version `0.0.2`, so I can't do much yet. Follow me and [my website](http://comdor.co) for updates on the next version.

**Comment by amihaiemil** [comment]
@charlesmike please indes [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

**Comment by charlesmike** [comment]
> @charlesmike please indes [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

@amihaiemil sorry I do not understand you. See [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post for more details.

**Comment by amihaiemil** [comment]
@charlesmike please index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

**Comment by charlesmike** [comment]
> @charlesmike please index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](https://charles.amihaiemil.com/logs.html?log=/d54a62ce-3e60-44c7-90de-da566e62fb7f.log).

**Comment by charlesmike** [comment]
> @charlesmike please index [this](https://amihaiemil.github.io/sitemap.xml) sitemap.

@amihaiemil Some steps failed when processing your command. See [logs](https://charles.amihaiemil.com/logs.html?log=/d54a62ce-3e60-44c7-90de-da566e62fb7f.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike try to index [this](https://amihaiemil.github.io/sitemap.xml) sitemap again...

**Comment by charlesmike** [comment]
> @charlesmike try to index [this](https://amihaiemil.github.io/sitemap.xml) sitemap again...

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](https://charles.amihaiemil.com/logs.html?log=/c1ef14e2-64bf-4e93-a2d3-10a567288f0a.log).

**Comment by charlesmike** [comment]
> @charlesmike try to index [this](https://amihaiemil.github.io/sitemap.xml) sitemap again...

@amihaiemil Some steps failed when processing your command. See [logs](https://charles.amihaiemil.com/logs.html?log=/c1ef14e2-64bf-4e93-a2d3-10a567288f0a.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/2018/09/30/project-versioning-with-rultor.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/2018/09/30/project-versioning-with-rultor.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](https://charles.amihaiemil.com/logs.html?log=/1153b954-a609-452e-ac8d-5814a40ce4c2.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/2018/09/30/project-versioning-with-rultor.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](https://charles.amihaiemil.com/logs.html?log=/1153b954-a609-452e-ac8d-5814a40ce4c2.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike delete the `amihaiemil.github.io` index pls

**Comment by charlesmike** [comment]
> @charlesmike delete the `amihaiemil.github.io` index pls

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See the [logs](http://charles.amihaiemil.com/logs.html?log=/1a095c3b-0bfb-47eb-bea0-bbc6966de3f2.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index site

**Comment by charlesmike** [comment]
> @charlesmike index site

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/f29b4b89-03b2-4614-9941-b7485c707498.log).

**Comment by charlesmike** [comment]
> @charlesmike index site

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/f29b4b89-03b2-4614-9941-b7485c707498.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index site pls

**Comment by charlesmike** [comment]
> @charlesmike index site pls

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/61ddb373-28f0-4e7a-a963-72901f657e86.log).

**Comment by charlesmike** [comment]
> @charlesmike index site pls

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/61ddb373-28f0-4e7a-a963-72901f657e86.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index site pls

**Comment by charlesmike** [comment]
> @charlesmike index site pls


@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/33ef8b6a-24bd-4c8d-b8ce-3844c6638005.log).

**Comment by charlesmike** [comment]
> @charlesmike index site pls


@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/33ef8b6a-24bd-4c8d-b8ce-3844c6638005.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).
