### ISSUE TITLE
"But how do you work without a model?"

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/amihaiemil.github.io#37]
For indexing

**Comment by amihaiemil** [comment]
@charlesmike please, index [this](http://amihaiemil.github.io/2017/11/04/but-how-do-you-work-without-a-model.html) new page

**Comment by charlesmike** [comment]
> @charlesmike please, index [this](http://amihaiemil.github.io/2017/11/04/but-how-do-you-work-without-a-model.html) new page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/f9c40be2-9ed4-48f2-91d9-d570935125e5.log).

**Comment by charlesmike** [comment]
> @charlesmike please, index [this](http://amihaiemil.github.io/2017/11/04/but-how-do-you-work-without-a-model.html) new page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/f9c40be2-9ed4-48f2-91d9-d570935125e5.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)
