### ISSUE TITLE
My Take On Object Naming

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/amihaiemil.github.io#41]
for indexing

**Comment by amihaiemil** [comment]
@charlesmike please, index [this](http://amihaiemil.github.io/2018/01/07/my-take-on-object-naming.html) new page

**Comment by charlesmike** [comment]
> @charlesmike please, index [this](http://amihaiemil.github.io/2018/01/07/my-take-on-object-naming.html) new page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/e6de2fce-22f2-4f21-9c15-146f3a45af4f.log).

**Comment by charlesmike** [comment]
> @charlesmike please, index [this](http://amihaiemil.github.io/2018/01/07/my-take-on-object-naming.html) new page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/e6de2fce-22f2-4f21-9c15-146f3a45af4f.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)
