### ISSUE TITLE
Teach Them The Language First

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/amihaiemil.github.io#45]
Before learning to work with a framework, a developer should first understand the basis of everything, the language and the ecosystem that is built around it.

**Comment by amihaiemil** [comment]
@charlesmike please, index [this](http://amihaiemil.github.io/2018/01/24/teach-them-the-language-first.html) new page

**Comment by amihaiemil** [comment]
@charlesmike please, index [this](http://amihaiemil.github.io/2018/01/24/teach-them-the-language-first.html) new page

**Comment by charlesmike** [comment]
> @charlesmike please, index [this](http://amihaiemil.github.io/2018/01/24/teach-them-the-language-first.html) new page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/1c369cd6-0ed4-4f44-8c03-3525d2096900.log).

**Comment by charlesmike** [comment]
> @charlesmike please, index [this](http://amihaiemil.github.io/2018/01/24/teach-them-the-language-first.html) new page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/1c369cd6-0ed4-4f44-8c03-3525d2096900.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)
