### ISSUE TITLE
refresh index

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/amihaiemil.github.io#55]

**Comment by amihaiemil** [comment]
@charlesmike delete `amihaiemil.github.io` index

**Comment by charlesmike** [comment]
> @charlesmike delete `amihaiemil.github.io` index

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See [logs](http://charles.amihaiemil.com/logs.html?log=/2dd967b3-46a4-45b8-ad14-71c3cc1443aa.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap, please

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/73316b77-cb42-4aa8-908f-f5e0e772514b.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/373d4bfe-4382-4717-a66f-332760d662eb.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/73316b77-cb42-4aa8-908f-f5e0e772514b.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/373d4bfe-4382-4717-a66f-332760d662eb.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/2c9c87d3-498a-47c1-9462-66dba644cffd.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/2c9c87d3-498a-47c1-9462-66dba644cffd.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/9eba8b25-1f80-40d4-a36c-0291c958f0f1.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/9eba8b25-1f80-40d4-a36c-0291c958f0f1.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/cb95c1f3-25d8-49c0-bbf5-b591509639dc.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/cb95c1f3-25d8-49c0-bbf5-b591509639dc.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike delete `amihaiemil.github.io` index

**Comment by charlesmike** [comment]
> @charlesmike delete `amihaiemil.github.io` index

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See [logs](http://charles.amihaiemil.com/logs.html?log=/e76e5922-1762-4947-b4de-139aaeb365d4.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/2b7edb30-a7b2-452e-9d68-4df124f08b52.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/2b7edb30-a7b2-452e-9d68-4df124f08b52.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/4c9024ae-788f-4d86-ac88-3d3daa5ad803.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/4c9024ae-788f-4d86-ac88-3d3daa5ad803.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/5f91f19d-6531-4418-bd2e-bd2622cfe4a6.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/5f91f19d-6531-4418-bd2e-bd2622cfe4a6.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/0188ee55-9a43-40af-93de-6c80cf1b8465.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/0188ee55-9a43-40af-93de-6c80cf1b8465.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/a13494df-25a0-420c-abee-a5c5a99ef69e.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/a13494df-25a0-420c-abee-a5c5a99ef69e.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike delete `amihaiemil.github.io` index

**Comment by charlesmike** [comment]
> @charlesmike delete `amihaiemil.github.io` index

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See [logs](http://charles.amihaiemil.com/logs.html?log=/dc78f553-13f1-4ec2-a47a-1af40b54eefd.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/7c025618-6ef2-4708-90dc-adf9ef421920.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/7c025618-6ef2-4708-90dc-adf9ef421920.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap, please

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/ab450ad0-c9c4-45d5-ae5a-0bd9d8afd96f.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/ab450ad0-c9c4-45d5-ae5a-0bd9d8afd96f.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/b8ad7e6b-39e1-4598-b1e8-cbd33baceb19.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](http://amihaiemil.github.io/sitemap.xml) sitemap, please

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/b8ad7e6b-39e1-4598-b1e8-cbd33baceb19.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike hello there

**Comment by charlesmike** [comment]
> @charlesmike hello there

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).
Also, [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post might be useful.

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap please

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/bb173074-e78e-4762-b915-b22c9f743f32.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/sitemap.xml) sitemap please

@amihaiemil Some steps failed when processing your command. See [logs](http://charles.amihaiemil.com/logs.html?log=/bb173074-e78e-4762-b915-b22c9f743f32.log) for details.
Try again and if the error persists please, open an [issue](https://github.com/opencharles/charles-rest/issues/new).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/2018/09/30/project-versioning-with-rultor.html) page

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/2018/09/30/project-versioning-with-rultor.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/944c3cfe-8ba0-46a8-adfa-487dd9dab687.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/2018/09/30/project-versioning-with-rultor.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See [logs](http://charles.amihaiemil.com/logs.html?log=/944c3cfe-8ba0-46a8-adfa-487dd9dab687.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike delete the `amihaiemil.github.io` index

**Comment by charlesmike** [comment]
> @charlesmike delete the `amihaiemil.github.io` index

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See the [logs](http://charles.amihaiemil.com/logs.html?log=/88bc6130-c942-4f89-a2fe-4f68169961e9.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index site please

**Comment by charlesmike** [comment]
> @charlesmike index site please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/9c2c4d25-42de-46fa-a8a0-2c20e017d91f.log).

**Comment by amihaiemil** [comment]
@charlesmike index site please

**Comment by charlesmike** [comment]
> @charlesmike index site please


@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/70a19e3f-d2cd-480e-a9b9-a97ddc947f42.log).

**Comment by charlesmike** [comment]
> @charlesmike index site please


@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/70a19e3f-d2cd-480e-a9b9-a97ddc947f42.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike delete index `amihaiemil.github.io`

**Comment by charlesmike** [comment]
> @charlesmike delete index `amihaiemil.github.io`

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See the [logs](http://charles.amihaiemil.com/logs.html?log=/8b460783-8a22-4f66-86b8-4cfab1877a7d.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index site

**Comment by charlesmike** [comment]
> @charlesmike index site

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/0f8cc18b-2f03-4565-9e76-f7017375bab9.log).

**Comment by charlesmike** [comment]
> @charlesmike index site

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/0f8cc18b-2f03-4565-9e76-f7017375bab9.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike delete the `amihaiemil.github.io` index

**Comment by charlesmike** [comment]
> @charlesmike delete the `amihaiemil.github.io` index

@amihaiemil the `amihaiemil.github.io` index was successfully deleted. 
Don't forget to remove the script form your website since the search will not work anymore.
See the [logs](http://charles.amihaiemil.com/logs.html?log=/abaf4449-0793-4e35-9700-1664039be39e.log) for details.

If you can spare a minute, please consider opening an issue [here](https://github.com/opencharles/charles-rest/issues/new),let us know why you stopped using this service, what you didn't like and what we could improve. Thanks!

**Comment by amihaiemil** [comment]
@charlesmike index site

**Comment by charlesmike** [comment]
> @charlesmike index site

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/6a607d67-e21d-48d7-a392-dc7bdfde53bb.log).
