### ISSUE TITLE
index new articles

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/amihaiemil.github.io#68]

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html).
Also, [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post might be useful.

**Comment by amihaiemil** [comment]
@charlesmike please index [this](https://amihaiemil.github.io/2018/12/09/builder-as-a-failfast-state-machine.html) page

**Comment by charlesmike** [comment]
> @charlesmike please index [this](https://amihaiemil.github.io/2018/12/09/builder-as-a-failfast-state-machine.html) page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/8453ea39-9cc8-4bde-a642-18e968bea930.log).

**Comment by charlesmike** [comment]
> @charlesmike please index [this](https://amihaiemil.github.io/2018/12/09/builder-as-a-failfast-state-machine.html) page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/8453ea39-9cc8-4bde-a642-18e968bea930.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/2019/01/23/apache-payara-lets-encrypt.html) page too

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/2019/01/23/apache-payara-lets-encrypt.html) page too

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/8a9f5c7e-47d0-4f90-a7c8-6bbbf5239f58.log).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/2019/01/23/apache-payara-lets-encrypt.html) page too

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/2019/01/23/apache-payara-lets-encrypt.html) page too

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/a009ca45-9bff-444e-97b3-36a9a63beb35.log).

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/hireme/hire.html) new page (hire me page)

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/hireme/hire.html) new page (hire me page)

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/f4992b98-929e-45cd-9ad4-800afa7b67ef.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/hireme/hire.html) new page (hire me page)

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/f4992b98-929e-45cd-9ad4-800afa7b67ef.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike please, index [this](https://amihaiemil.github.io/2019/03/31/polymorphic-input-output-data.html) new page

**Comment by charlesmike** [comment]
> @charlesmike please, index [this](https://amihaiemil.github.io/2019/03/31/polymorphic-input-output-data.html) new page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/bbc440ff-bc22-4b58-9c7f-edd698009be7.log).

**Comment by charlesmike** [comment]
> @charlesmike please, index [this](https://amihaiemil.github.io/2019/03/31/polymorphic-input-output-data.html) new page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/bbc440ff-bc22-4b58-9c7f-edd698009be7.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike please, index [this](https://amihaiemil.github.io/2019/05/12/new-project-checklist.html) new page

**Comment by charlesmike** [comment]
> @charlesmike please, index [this](https://amihaiemil.github.io/2019/05/12/new-project-checklist.html) new page

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/fa0e0ab9-96e8-462d-bba3-1118bdc820dc.log).

**Comment by charlesmike** [comment]
> @charlesmike please, index [this](https://amihaiemil.github.io/2019/05/12/new-project-checklist.html) new page

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/fa0e0ab9-96e8-462d-bba3-1118bdc820dc.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)

**Comment by amihaiemil** [comment]
@charlesmike index [this](https://amihaiemil.github.io/2019/06/12/hide-it-all.html) new page please

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/2019/06/12/hide-it-all.html) new page please

@amihaiemil thank you for the command, the indexing process started just now. I will let you know of the outcome shortly. In the meantime, you can check the logs [here](http://charles.amihaiemil.com/logs.html?log=/b2c98928-ad9b-45f9-9e24-7cea03394ad8.log).

**Comment by charlesmike** [comment]
> @charlesmike index [this](https://amihaiemil.github.io/2019/06/12/hide-it-all.html) new page please

@amihaiemil Index command executed successfully! 
 Add the widget [script](https://github.com/opencharles/charles-search-box#reactjs-search-box-component) to the website in order to make the search functionality available.

 See the [logs](http://charles.amihaiemil.com/logs.html?log=/b2c98928-ad9b-45f9-9e24-7cea03394ad8.log) for more details. 
 If you notice any inexplicable errors, please open an issue [here](https://github.com/opencharles/charles-rest/issues/new)
